import os
import json
import logging
from typing import List, Optional

import vertexai
from vertexai.generative_models import GenerativeModel, GenerationConfig
from vertexai.preview.vision_models import ImageGenerationModel

from models import StoryConfig, CardConfig

logger = logging.getLogger(__name__)

class AIService:
    def __init__(self):
        project = os.getenv("GOOGLE_CLOUD_PROJECT")
        # us-central1 is generally the best region for generative models if not specified
        location = os.getenv("GCP_LOCATION", "us-central1")
        vertexai.init(project=project, location=location)

        gemini_model_id = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
        self.gemini_model = GenerativeModel(gemini_model_id)
        
        imagen_model_id = os.getenv("IMAGEN_MODEL", "imagen-3.0-generate-002")
        self.imagen_model = ImageGenerationModel.from_pretrained(imagen_model_id)

    def generate_story_narrative(self, topic: str, input_text: Optional[str] = None, style: str = "Default") -> StoryConfig:
        prompt = f"""You are a creative storyteller. Turn the following concept into a 5-card illustrated story.
Topic: {topic}
Additional context: {input_text or "None"}
Art Style: {style}

Guidelines:
- Create exactly 5 cohesive scenes in chronological order.
- The visual prompts MUST maintain character and setting consistency across all 5 scenes. Describe the main character's appearance in detail in EVERY visual prompt.
- For each scene, provide a title, a short caption, and a detailed visual prompt for an image generator (like Imagen 3).
- Output must be strictly valid JSON.
"""
        schema = {
            "type": "OBJECT",
            "properties": {
                "summary": {"type": "STRING"},
                "cards": {
                    "type": "ARRAY",
                    "items": {
                        "type": "OBJECT",
                        "properties": {
                            "title": {"type": "STRING"},
                            "caption": {"type": "STRING"},
                            "visual_prompt": {"type": "STRING"}
                        },
                        "required": ["title", "caption", "visual_prompt"]
                    }
                }
            },
            "required": ["summary", "cards"]
        }
        
        config = GenerationConfig(
            response_mime_type="application/json",
            response_schema=schema,
            temperature=0.7,
        )

        try:
            response = self.gemini_model.generate_content(
                contents=prompt,
                generation_config=config,
            )
            data = json.loads(response.text)
            
            # Ensure exactly 5 cards
            if "cards" in data and len(data["cards"]) > 5:
                data["cards"] = data["cards"][:5]
            elif "cards" in data and len(data["cards"]) < 5:
                # Pad if too few (rare but possible and requested by PRD)
                while len(data["cards"]) < 5 and len(data["cards"]) > 0:
                    data["cards"].append(data["cards"][-1])

            return StoryConfig(**data)
        except Exception as e:
            logger.error(f"Failed to generate story narrative: {e}")
            raise ValueError(f"Failed to generate structural story: {str(e)}")

    def generate_story_image(self, visual_prompt: str, style: str) -> bytes:
        full_prompt = f"{visual_prompt}. Art style: {style}"
        
        try:
            images = self.imagen_model.generate_images(
                prompt=full_prompt,
                number_of_images=1,
                aspect_ratio="1:1"
            )
            
            if not images:
                raise ValueError("No image generated by Imagen.")
            
            # `images[0]._image_bytes` is typically how we get raw bytes from the Image object in this SDK
            return images[0]._image_bytes
        except Exception as e:
            logger.error(f"Failed to generate image: {e}")
            raise ValueError(f"Failed to generate image: {str(e)}")
